#!/usr/bin/perl
#-------------------------------------------------------------------------
#
# gen_pathtags.pl
#	  Derive the set of Path-subtype NodeTags from src/include/nodes/pathnodes.h
#	  and emit an X-macro header consumed by pg_pathcheck.c.
#
#	  A struct S is a Path subtype iff S is "Path" itself, or S's first data
#	  field has a type that is already a Path subtype.  Structs marked with
#	  pg_node_attr(abstract) participate in inheritance but do not receive
#	  their own NodeTag (gen_node_support.pl does the same upstream), so we
#	  skip emitting X(T_S) for them.
#
#	  In addition to PATH_TAG_LIST, we emit a structural hash
#	  PPC_PATH_HASH_T_<Subtype> for every concrete Path subtype.  The hash
#	  is derived from the struct's body after comments, pg_node_attr(...)
#	  invocations and redundant whitespace have been stripped, so cosmetic
#	  edits do not fire the guard.  Any field addition, removal, rename,
#	  type change or reordering does.
#
# usage:
#	  perl gen_pathtags.pl <path-to-pathnodes.h> <output-header>
#
# Copyright (c) 2026 Andrei Lepikhov
# Released under the MIT License; see LICENSE in the project root.
#
#-------------------------------------------------------------------------

use strict;
use warnings FATAL => 'all';
use Digest::MD5 qw(md5_hex);

my $input  = shift @ARGV;
my $output = shift @ARGV;

defined $input  or die "usage: $0 <pathnodes.h> <output-header>\n";
defined $output or die "usage: $0 <pathnodes.h> <output-header>\n";

open(my $in, '<', $input) or die "could not open \"$input\": $!";
my $src = do { local $/; <$in> };
close $in;

# Strip C comments; they can hide matching tokens in our regexes.
$src =~ s{/\*.*?\*/}{}gs;
$src =~ s{//[^\n]*}{}g;

# Walk every "typedef struct Name { ... } [Alias];".  We parse the body to
# (a) record whether the struct is abstract, and (b) find the first data
# field's type so we can climb the inheritance chain.
my %first_field_type;
my %is_abstract;
my %body_hash;
my @decl_order;

while ($src =~ /typedef \s+ struct \s+ (\w+) \s* \{ ( (?: [^{}]++ | \{[^{}]*\} )* ) \}/gxs)
{
	my ($name, $body) = ($1, $2);

	# Remember pg_node_attr(abstract) before we strip annotations away.
	# Handle one level of nested parens (e.g. pg_node_attr(array_size(n))).
	$is_abstract{$name} = 1
		if $body =~ /pg_node_attr \s* \( (?: [^()]* | \([^()]*\) )* \b abstract \b (?: [^()]* | \([^()]*\) )* \)/x;

	# Remove every pg_node_attr(...) invocation (struct-level and trailing
	# field-level), so that split-by-semicolon yields clean field declarations
	# and so that annotation changes do not perturb the structural hash.
	1 while $body =~ s/pg_node_attr \s* \( (?: [^()]* | \([^()]*\) )* \)//gx;

	# Canonical form for hashing: all whitespace collapsed to single spaces.
	# Comments are already stripped at file level; pg_node_attr invocations
	# were just removed.  What remains is the field layout, which is exactly
	# what walk_path() makes assumptions about.
	my $canonical = $body;
	$canonical =~ s/\s+/ /g;
	$canonical =~ s/^\s+|\s+$//g;
	$body_hash{$name} = substr(md5_hex($canonical), 0, 16);

	my $first_type;
	for my $field (split /;/, $body)
	{
		$field =~ s/^\s+|\s+$//g;
		next if $field eq '';

		# Skip the NodeTag header on the root of an inheritance chain;
		# we want the first *substantive* struct field.
		next if $field =~ /^NodeTag\s+type\b/;

		# Match "TypeName [*] fieldname".  TypeName is the first identifier.
		if ($field =~ /^([A-Za-z_]\w*)\s+\*?\s*[A-Za-z_]\w*/)
		{
			$first_type = $1;
			last;
		}
	}

	$first_field_type{$name} = $first_type;
	push @decl_order, $name;
}

# Transitive classification: seed with Path, iterate until fixed point.
my %is_path = (Path => 1);
my $changed = 1;
while ($changed)
{
	$changed = 0;
	for my $name (@decl_order)
	{
		next if $is_path{$name};
		my $parent = $first_field_type{$name};
		if (defined $parent && $is_path{$parent})
		{
			$is_path{$name} = 1;
			$changed = 1;
		}
	}
}

# Emit concrete (non-abstract) Path subtypes in declaration order.
my @emitted = grep { $is_path{$_} && !$is_abstract{$_} } @decl_order;

die "$0: no Path subtypes detected in $input — parser broken?\n"
	if @emitted == 0;

open(my $out, '>', $output) or die "could not open \"$output\" for writing: $!";

print $out <<"EOT";
/*-------------------------------------------------------------------------
 *
 * pathtags_generated.h
 *	  Auto-generated descriptor of every concrete Path subtype in
 *	  src/include/nodes/pathnodes.h.  DO NOT EDIT BY HAND — regenerated by
 *	  contrib/pg_pathcheck/gen_pathtags.pl on every build.
 *
 *	  PATH_TAG_LIST(X) expands X(T_<Subtype>) in declaration order.
 *	  Typical use:
 *
 *		switch (tag)
 *		{
 *	#define PPC_X(t) case t:
 *			PATH_TAG_LIST(PPC_X)
 *	#undef PPC_X
 *				return true;
 *			default:
 *				return false;
 *		}
 *
 *	  In addition, PPC_PATH_HASH_T_<Subtype> gives a 64-bit structural
 *	  hash of that subtype's body — stable under cosmetic edits, changes
 *	  on any real field addition/removal/rename/type-change/reorder.
 *	  pg_pathcheck.c cross-checks these against a hand-blessed mirror so
 *	  an upstream layout change fails the build before walk_path() can
 *	  silently miss a new sub-path field.
 *
 *-------------------------------------------------------------------------
 */
#ifndef PATHTAGS_GENERATED_H
#define PATHTAGS_GENERATED_H

#define PATH_TAG_LIST(X) \\
EOT

for (my $i = 0; $i < @emitted; $i++)
{
	my $trailer = ($i < $#emitted) ? ' \\' : '';
	print $out "\tX(T_$emitted[$i])$trailer\n";
}

print $out "\n";

# Longest tag name, so we can align the hash constants for readability.
my $maxlen = 0;
for my $name (@emitted)
{
	my $len = length("PPC_PATH_HASH_T_$name");
	$maxlen = $len if $len > $maxlen;
}

for my $name (@emitted)
{
	my $symbol = "PPC_PATH_HASH_T_$name";
	my $pad	   = ' ' x ($maxlen - length($symbol));
	print $out "#define $symbol$pad 0x$body_hash{$name}ULL\n";
}

print $out "\n#endif\t\t\t\t\t\t\t/* PATHTAGS_GENERATED_H */\n";

close $out;
